name: "1. Build main images"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */1 * * *

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build image"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:main

      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Check the latest verion
        run: |
          [ -e README.md ] && NOW=$(awk '/^正式版:/{print $NF}' README.md)
          LATEST=$(wget -qO- "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | awk -F '"' '/tag_name/{print $4}')
          echo " NOW: $NOW"
          echo " LATEST: $LATEST"
          if [ "$NOW" != "$LATEST" ]; then
            sed -i "/^正式版:/s/\(.*: \).*/\1$LATEST/" README.md
            echo "VERSION=$LATEST" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        if: ${{ env.VERSION != '' }}
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          file: main/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          tags: ${{ env.DOCKERHUB_REPOSITORY }}

      - name: Upload to repository
        if: ${{ env.VERSION != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Build ${{ env.VERSION }} by Github Actions, ${{ env.DATE }}